<?php
/**
 * XAMPP Local Database Setup Tool
 * Create a local D.env file with XAMPP MySQL credentials
 */
require_once '../../config/SecureKeyManager.php';
require_once '../../config/SecureConfig.php';

echo "<h1>🗄️ XAMPP Local Database Setup</h1>";
echo "<p>This tool will create a D.env file for local XAMPP development</p>";

if (isset($_POST['setup_local'])) {
    try {
        // Initialize encryption
        SecureKeyManager::init();
        
        echo "<div style='background: #fff3cd; color: #856404; padding: 20px; border-radius: 10px; margin: 20px 0;'>";
        echo "<h2>🔄 Setting up local XAMPP database...</h2>";
        
        // XAMPP default credentials
        $dbHost = 'localhost';
        $dbName = 'luthor_db';
        $dbUser = 'root';
        $dbPassword = ''; // XAMPP default empty password
        
        echo "<p>📝 Using XAMPP default credentials:</p>";
        echo "<ul>";
        echo "<li><strong>Host:</strong> {$dbHost}</li>";
        echo "<li><strong>Database:</strong> {$dbName}</li>";
        echo "<li><strong>Username:</strong> {$dbUser}</li>";
        echo "<li><strong>Password:</strong> (empty - XAMPP default)</li>";
        echo "</ul>";
        
        // Test connection first
        echo "<p>🧪 Testing XAMPP MySQL connection...</p>";
        try {
            $testPdo = new PDO("mysql:host={$dbHost};charset=utf8mb4", $dbUser, $dbPassword, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
            ]);
            echo "<p>✅ XAMPP MySQL connection successful</p>";
            
            // Create database if it doesn't exist
            echo "<p>🗄️ Creating database if needed...</p>";
            $testPdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            echo "<p>✅ Database '{$dbName}' ready</p>";
            
            // Test connection to the specific database
            $dbTestPdo = new PDO("mysql:host={$dbHost};dbname={$dbName};charset=utf8mb4", $dbUser, $dbPassword, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
            ]);
            echo "<p>✅ Database connection test successful</p>";
            
        } catch (PDOException $e) {
            throw new Exception("XAMPP MySQL connection failed: " . $e->getMessage() . "\n\nPlease make sure XAMPP MySQL is running!");
        }
        
        // Encrypt credentials
        echo "<p>🔐 Encrypting credentials...</p>";
        $keyManager = new SecureKeyManager();
        $keys = $keyManager->getEncryptionKeys();
        
        $encryptedDbUser = $keyManager->encryptData($dbUser, $keys['encryption_key']);
        $encryptedDbPassword = $keyManager->encryptData($dbPassword, $keys['encryption_key']);
        $encryptedAdminPassword = $keyManager->encryptData('admin123', $keys['encryption_key']);
        
        // Create D.env content for XAMPP
        $envContent = "# XAMPP Local Database Configuration\n";
        $envContent .= "# Generated by XAMPP Setup Tool\n";
        $envContent .= "# D.env - Database Environment File with Encrypted Credentials\n";
        $envContent .= "DB_HOST={$dbHost}\n";
        $envContent .= "DB_NAME={$dbName}\n";
        $envContent .= "DB_USER_ENCRYPTED={$encryptedDbUser}\n";
        $envContent .= "DB_PASSWORD_ENCRYPTED={$encryptedDbPassword}\n";
        $envContent .= "\n# Admin Configuration\n";
        $envContent .= "ADMIN_PASSWORD_ENCRYPTED={$encryptedAdminPassword}\n";
        $envContent .= "\n# Application Settings\n";
        $envContent .= "APP_ENV=development\n";
        $envContent .= "APP_DEBUG=true\n";
        $envContent .= "\n# Security Settings\n";
        $envContent .= "ENCRYPTION_ENABLED=true\n";
        $envContent .= "SESSION_SECURE=false\n";
        $envContent .= "\n# XAMPP Development Settings\n";
        $envContent .= "LOCAL_DEVELOPMENT=true\n";
        $envContent .= "SETUP_TIMESTAMP=" . date('Y-m-d H:i:s') . "\n";
        $envContent .= "\n# File generated by XAMPP Setup Tool on " . date('Y-m-d H:i:s') . "\n";
        $envContent .= "# D.env contains encrypted database credentials for secure storage\n";
        
        // Save D.env file
        $envPath = __DIR__ . '/../../secure/D.env';
        file_put_contents($envPath, $envContent);
        echo "<p>✅ Created: D.env file with XAMPP encrypted credentials</p>";
        
        echo "<div style='background: #d4edda; color: #155724; padding: 15px; border-radius: 5px; margin: 15px 0;'>";
        echo "<h3>🎉 XAMPP Database Setup Complete!</h3>";
        echo "<p><strong>Configuration:</strong></p>";
        echo "<ul>";
        echo "<li>✅ D.env - XAMPP database credentials (encrypted)</li>";
        echo "<li>✅ Database: {$dbName} on localhost</li>";
        echo "<li>✅ Connection tested successfully</li>";
        echo "<li>✅ Ready for local development</li>";
        echo "</ul>";
        echo "</div>";
        
        echo "<div style='background: #e9ecef; color: #495057; padding: 15px; border-radius: 5px; margin: 15px 0;'>";
        echo "<h4>📋 Next Steps:</h4>";
        echo "<ul>";
        echo "<li>Test the database connection using the test tool</li>";
        echo "<li>Run your application to verify everything works</li>";
        echo "<li>Use the debug dashboard to manage your database</li>";
        echo "</ul>";
        echo "</div>";
        
        echo "</div>";
        
    } catch (Exception $e) {
        echo "<div style='background: #f8d7da; color: #721c24; padding: 15px; border-radius: 5px; margin: 15px 0;'>";
        echo "<h3>❌ Setup Failed</h3>";
        echo "<p>Error: " . htmlspecialchars($e->getMessage()) . "</p>";
        echo "</div>";
    }
}

// Show current D.env status
echo "<div style='background: #f8f9fa; padding: 20px; border-radius: 10px; margin: 20px 0;'>";
echo "<h2>📊 Current D.env Status</h2>";

$envPath = __DIR__ . '/../../secure/D.env';
if (file_exists($envPath)) {
    $envContent = file_get_contents($envPath);
    $size = filesize($envPath);
    $date = filemtime($envPath);
    
    echo "<p>✅ <strong>D.env file exists</strong></p>";
    echo "<p><strong>Size:</strong> " . number_format($size) . " bytes</p>";
    echo "<p><strong>Modified:</strong> " . date('Y-m-d H:i:s', $date) . "</p>";
    
    // Check what host it's configured for
    if (strpos($envContent, 'DB_HOST=localhost') !== false) {
        echo "<p><strong>Configuration:</strong> 🏠 XAMPP Local (localhost)</p>";
    } elseif (strpos($envContent, 'mysql-200-133.mysql.prositehosting.net') !== false) {
        echo "<p><strong>Configuration:</strong> 🌐 Remote Server (mysql-200-133.mysql.prositehosting.net)</p>";
    } else {
        echo "<p><strong>Configuration:</strong> ❓ Unknown host</p>";
    }
    
} else {
    echo "<p>❌ <strong>D.env file not found</strong></p>";
    echo "<p>Create a D.env file to configure your database connection.</p>";
}

echo "</div>";

// Setup form
echo "<div style='background: #e8f4f8; color: #0c5460; padding: 20px; border-radius: 10px; margin: 20px 0;'>";
echo "<h2>🗄️ Setup XAMPP Local Database</h2>";
echo "<p>This will create a D.env file configured for XAMPP local development.</p>";

echo "<div style='background: #fff3cd; color: #856404; padding: 15px; border-radius: 5px; margin: 15px 0;'>";
echo "<h4>📋 Requirements:</h4>";
echo "<ul>";
echo "<li>XAMPP must be running with MySQL service started</li>";
echo "<li>Encryption keys must be generated (K.env file)</li>";
echo "<li>This will overwrite existing D.env file</li>";
echo "</ul>";
echo "</div>";

echo "<div style='text-align: center; margin: 20px 0;'>";
echo "<form method='post'>";
echo "<button type='submit' name='setup_local' style='background: #28a745; color: white; border: none; padding: 15px 30px; border-radius: 5px; cursor: pointer; font-size: 16px; font-weight: bold;'>";
echo "🗄️ Setup XAMPP Database";
echo "</button>";
echo "</form>";
echo "</div>";

echo "</div>";

echo "<div style='text-align: center; margin-top: 30px;'>";
echo "<a href='test_d_env_connection.php' style='background: #17a2b8; color: white; padding: 12px 24px; text-decoration: none; border-radius: 25px; font-weight: 500; margin-right: 10px;'>🧪 Test Connection</a>";
echo "<a href='recovery_tool.php' style='background: #dc3545; color: white; padding: 12px 24px; text-decoration: none; border-radius: 25px; font-weight: 500; margin-right: 10px;'>🚨 Recovery Tool</a>";
echo "<a href='../debug_dashboard.php' style='background: #007cba; color: white; padding: 12px 24px; text-decoration: none; border-radius: 25px; font-weight: 500;'>← Back to Dashboard</a>";
echo "</div>";
?>

<style>
body { 
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
    margin: 20px; 
    background: #f8f9fa;
}
h1, h2, h3, h4 { 
    color: #2c3e50; 
    margin-top: 0;
}
button:hover {
    opacity: 0.9;
    transform: translateY(-1px);
    transition: all 0.2s ease;
}
a:hover {
    opacity: 0.9;
    transform: translateY(-1px);
    transition: all 0.2s ease;
}
</style>
